title: Minimalist theme
logo: /assets/img/developerPic.jpeg
email: edalbadi@gmail.com
description: Minimalist is a theme powered by Jekyll. It is modified based on the Minimal theme.
show_downloads: false
google_analytics: G-ZLK2GHB055
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji


# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin-in"></i>
    link: https://www.linkedin.com/in/ebanos/
  - name: CDMX, México
    icon: <i class="fa-solid fa-location-dot"></i>
    link: #
  - name: 55-13-01-12-85
    icon: <i class="fa-solid fa-phone"></i>
    link: #
  - name: edalbadi@gmail.com
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:edalbadi@gmail.com



